### ISSUE TITLE
Getting an unhandled exception when calling  Wakelock.enable()

### ISSUE THREAD

**Issue by jaca420** [creativecreatorormaybenot/wakelock#178]
So I have a method that enables location tracking and I want `Wakelock` to be enabled just when this is on. When the user turns it off I call `Wakelock.disable()`. On each of these calls the exception is thrown.

```
void startLocationTracking() async {

     Wakelock.enable();

      await BackgroundLocation.startLocationService(distanceFilter: 15);

      BackgroundLocation.getLocationUpdates((location) {
        setState(() {
          latitude = location.latitude.toString();
          longitude = location.longitude.toString();
          accuracy = location.accuracy.toString();
          altitude = location.altitude.toString();
          bearing = location.bearing.toString();
          speed = location.speed.toString();
        });

      });
    }
```

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:89:7)
<asynchronous suspension>
#1      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:20:5)
<asynchronous suspension>
#2      HomeScreenState.build.startLocationTracking.<anonymous closure> (package:gtok/Screens/home_screen.dart:236:9)
<asynchronous suspension>
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1468, on macOS 12.3.1 21E258 darwin-x64, locale en-EN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by creativecreatorormaybenot** [comment]
Hi - I think the platform channels are properly configured and cannot reproduce this issue.

Could you make sure that you are running the latest stable build of Flutter with the latest version of the plugin and that you have executed `flutter clean` before building your app? If the issue still persists, I am glad to reopen this issue.
