### ISSUE TITLE
Message corrupted, Failed to handle message

### ISSUE THREAD

**Issue by jbj88817** [creativecreatorormaybenot/wakelock#179]
Got the below issue, I'm on flutter 3.3.0:

```
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): Failed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): java.lang.IllegalArgumentException: Message corrupted
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:450)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:340)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:424)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:340)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.plugin.common.StandardMessageCodec.decodeMessage(StandardMessageCodec.java:89)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:218)
[GETX] Instance "SongController" has been initialized
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at android.os.Handler.handleCallback(Handler.java:938)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at android.os.Looper.loopOnce(Looper.java:226)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at android.os.Looper.loop(Looper.java:313)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/BasicMessageChannel#dev.flutter.pigeon.WakelockApi.toggle(24941): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter (24941): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (24941): #0      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:89:7)
E/flutter (24941): <asynchronous suspension>
E/flutter (24941): #1      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:20:5)
E/flutter (24941): <asynchronous suspension>
```

**Comment by miracoli** [comment]
Same issue here. I'm on Flutter 3.0.5. Does not happen after downgrading to 0.6.1+2.

**Comment by marianhlavac** [comment]
**Confirmed @miracoli 's solution as working.**

Still, I added the package few days ago using the `flutter pub add wakelock` command and it automatically assumed the version 0.4.0, therefore something is still wrong.

**Comment by miracoli** [comment]
Yesterday a new version of [wakelock_windows](https://github.com/creativecreatorormaybenot/wakelock/releases/tag/wakelock_windows-v0.2.1) was released. That should fix this issue (at least it did for me). Could you run `flutter pub upgrade` and check if the correct version gets pulled?

**Comment by ostk0069** [comment]
This problem happens on Android as well.
Is there any updates?

**Comment by kugesh-Rajasekaran** [comment]
Same here. Solves when I update the version from 0.4.0 to 0.6.2.

**Comment by creativecreatorormaybenot** [comment]
I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.
